### ISSUE TITLE
Add Prettier plugin for Tailwind CSS

### ISSUE THREAD

**Issue by JuanPabloDiaz** [tech-conferences/confs.tech#637]
#### Suggestion: Integrate Prettier with Tailwind CSS Plugin for Consistent Styling Across Environments

To enhance our project's code consistency and accommodate various developer environments, I recommend integrating the [Prettier plugin for Tailwind CSS](https://github.com/tailwindlabs/prettier-plugin-tailwindcss). This addition will align our styling efforts, especially since we're already utilizing `eslint` for code formatting.

The integration with Prettier and its Tailwind CSS plugin ensures that our codebase remains consistent, regardless of individual VS Code configurations. This approach not only streamlines the development process but also minimizes the potential for stylistic discrepancies across contributions.

Here's a proposed `.prettierrc.json` configuration to consider:

```json
// .prettierrc.json
{
  "semi": true,
  "tabWidth": 2,
  "useTabs": false,
  "singleQuote": true,
  "trailingComma": "es5",
  "bracketSpacing": true,
  "jsxBracketSameLine": true,
  "arrowParens": "avoid",
}
```
That last past is probably already handled by the `format` command but I would like a solution that format the code regardless of the VS code configuration.

This setup will help maintain a unified code style, making our project more accessible to new contributors and reducing the overhead for code reviews.

Looking forward to your thoughts on this proposal.

**Comment by nimzco** [comment]
Sounds good to me! Happy to see a PR to see how the CSS will be updated. :)

**Comment by JuanPabloDiaz** [comment]
I was reading about husky and I noticed that its being use in the repo as well. 
![image](https://github.com/tech-conferences/confs.tech/assets/25883220/2bc44da2-c9f5-4d7e-aeb4-47904631260f)

**Comment by JuanPabloDiaz** [comment]
I am sorry but the repo does not use tailwind at all. I just realized that it is using SCSS for all the styling. LOL

I still want to work on the solution to ensure a formatting rules regardless of whether developers manually format their code.

**Comment by nimzco** [comment]
Haha that's true, I thought it was a catch-all kind of linter.

You can run npm lint --fix locally, otherwise I believe you can activate a settings on VSCode to auto format based on eslint

**Comment by JuanPabloDiaz** [comment]
I found a better approach by running Prettier as a GitHub Action:

```yml
name: Check Code with Prettier

on:
  pull_request:
    branches:
      - "main"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Download dependencies
        run: npm ci
      - name: Run prettier
        run: npm run format
```
What do you think @nimzco?

**Comment by nimzco** [comment]
That will "pretty" the code on the CI action but won't add a new commit to the branch though.
Also, I don't know why, but when I ran this command locally, it wasn't formatting the file I had to format, so I'm a bit confused on the current config :/

**Comment by JuanPabloDiaz** [comment]
> That will "pretty" the code on the CI action but won't add a new commit to the branch though.

Update to "Format Code with Prettier"

```yml
name: Format Code with Prettier

on:
  pull_request:
    branches:
      - "main"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run prettier

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push changes
        if: env.changes_detected == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: fix formatting issues"
          git push origin HEAD:${{ github.head_ref }}
```
- Ensure Workflow read and write permissions are enable
- Add script:
```json
"scripts": {
  "prettier": "npx prettier --write \"**/*.{ts,tsx,}\""
}
```
This approach will Commit and Push changes.
Is this better @nimzco? the workflow works for me in a personal repo
